### ISSUE TITLE
Don't want to display 1/1 at the  top right corner

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#10]
I never use tabs. So I don't want to display 1/1 at the top right corner.

**Comment by mg979** [comment]
Setting:

        let g:xtabline_settings.tab_number_in_buffer_mode = 0

If there is more than one open tab, it still shows number.
Please reopen if it doesn't work.

**Comment by mg979** [comment]
Edit:

        let g:xtabline_settings.tab_number_in_buffers_mode = 0

(buffers, not buffer)

**Comment by yutakatay** [comment]
Thank you for quick response.

It works.
But it didn't work when let g:xtabline_settings.show_right_corner = 0` was set.

**Comment by mg979** [comment]
Mm ok I'll fix that.

**Comment by mg979** [comment]
It should be fixed now.

**Comment by yutakatay** [comment]
It's fixed.

Thank you very much!
