### ISSUE TITLE
Weird cursor movements

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#13]
### Actual Behavior

![Peek 2020-08-27 18-18_bad](https://user-images.githubusercontent.com/8683947/91422205-d0d8ea00-e891-11ea-8bbd-ff050a4f9303.gif)

### Expected Behavior

![Peek 2020-08-27 18-18](https://user-images.githubusercontent.com/8683947/91422210-d20a1700-e891-11ea-95e7-5ff5c2042017.gif)

I think it's because of this line in this commit(9f1cccea0f0ebb2e8be13417ce45f8ea54fe0334).

https://github.com/mg979/vim-xtabline/blob/9f1cccea0f0ebb2e8be13417ce45f8ea54fe0334/autoload/xtabline.vim#L412

**Comment by mg979** [comment]
Did you test it without that line? Because that line only triggers when you leave the command line. Anyway I don't have this bug, so I'm not sure it's this plugin.

Output of `:verbose autocmd CursorMoved`?

**Comment by yutakatay** [comment]
oh, that's true. I cannot reproduce this minimal vimrc.

```vim
syntax on
filetype plugin indent on

if has('vim_starting')
  let s:pluin_manager_dir='~/.vim/plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif

call plug#begin('~/.vim/plugged')
Plug 'mg979/vim-xtabline'
call plug#end()
```

That seems to be due to conflicts with other plugins. I'll look into it some more.
Sorry.

**Comment by yutakatay** [comment]
OK. I could reproduce it.

This is minimal vimrc.
```vim
syntax on
filetype plugin indent on

if has('vim_starting')
  let s:pluin_manager_dir='~/.vim/plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif

call plug#begin('~/.vim/plugged')
Plug 'rhysd/accelerated-jk'
Plug 'mg979/vim-xtabline'
call plug#end()

let g:accelerated_jk_acceleration_table = [30,60,80,85,90,95,100]
nmap <expr> j v:count ? '<Plug>(accelerated_jk_j)' : '<Plug>(accelerated_jk_gj)'
nmap <expr> k v:count ? '<Plug>(accelerated_jk_k)' : '<Plug>(accelerated_jk_gk)'
```

It seems to conflict with the settings of https://github.com/rhysd/accelerated-jk.
I decided to turn off accelerated-jk because I don't use it very often.

So I will close this issue. Sorry for the disturbance.
