### ISSUE TITLE
Get an error in Neovim's floating window

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#15]
Sorry to bring up the issue so often.

Floating widows in Neovim now give me an error from this commit(34485e367289bf80a0e6d36f8bc8386ff02ca44f).

```
:message
Error detected while processing function xtabline#render#tabline[18]..<SNR>47_render_buffers[31]..<lambda>24:
line    1:
E716: Key not present in Dictionary: 2
Error detected while processing function xtabline#render#tabline[18]..<SNR>47_render_buffers[31]..<lambda>24:
line    1:
E116: Invalid arguments for function get
Error detected while processing function xtabline#render#tabline[18]..<SNR>47_render_buffers[31]..<lambda>24:
line    1:
E15: Invalid expression: get(s:X.Buffers, nr, s:X._buffers[nr])
Error detected while processing function xtabline#render#tabline[18]..<SNR>47_render_buffers:
line   31:
E121: Undefined variable: special
Error detected while processing function xtabline#render#tabline[18]..<SNR>47_render_buffers:
line   31:
```

I know you are not using Neovim. But if you can fix it I would be happy.

### Reproduce step

1. Use this minimal vimrc. `nvim -u /tmp/mini.vim /tmp/mini.vim`

```vim
" minimal_vimrc
syntax enable
filetype plugin indent on

if has('vim_starting')
	let s:pluin_manager_dir='~/.vim/plugged/vim-plug'
	execute 'set runtimepath+=' . s:pluin_manager_dir
endif

call plug#begin('~/.vim/plugged')
Plug 'mg979/vim-xtabline'
call plug#end()

let g:xtabline_settings = {}
let g:xtabline_settings.tabline_modes = ['buffers', 'tabs', 'arglist']
```

2. `:let buf = nvim_create_buf(v:false, v:true)`
3. `:let win = nvim_open_win(buf, 0,  {'relative': 'cursor', 'width': 10, 'height': 2, 'col': 0, 'row': 1, 'anchor': 'NW', 'style': 'minimal
'} )`
4. Error message is displayed

### My environment

vim: Neovim v0.5.0-709-g4f8d98e58
OS: ArchLinux
vim-xtabline: 34485e367289bf80a0e6d36f8bc8386ff02ca44f

**Comment by mg979** [comment]
This was my fault, I reverted this commit on master. I have to test better this change, I thought it was a bit risky. Please leave this open, I'll have to fix it.

**Comment by mg979** [comment]
Can you update master and tell me if it's fixed? thanks

**Comment by yutakatay** [comment]
It's fixed! Thank you very much.
