### ISSUE TITLE
[Question] How to ignore a specific buffer in XTabNextBuffer

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#18]
I'm using buffers-mode.
I want to ignore a specific buffer when moving with XTabNextBuffer/XTabPrevBuffer.

How can I customize this plugin to ignore a specific type (filetype or buffer name or something)?

**Comment by mg979** [comment]
Can you provide a more specific example? You want to ignore it for which reason?

**Comment by mg979** [comment]
Anyway you can try:

    let g:xtabline.Buffers[buffer_number].special = 1

(not sure if it would work)

**Comment by yutakatay** [comment]
OK, sure. I'm using https://github.com/Xuyuanp/scrollbar.nvim plugin with xtabline. 
With that setting, if I use XTabNextBuffer, the scroll bar will appear.(scrollbar is floating window)

The scroll bar filetype is set to `scrollbar`.
So I want to customize it so that I don't switch to that buffer when `&ft ==? scrollbar`.

**Comment by yutakatay** [comment]
I also tried `let g:xtabline.xtabline._buffers[buffer_number].special = 1`, but scrollbar buffer is displayed.

**Comment by mg979** [comment]
> I also tried let g:xtabline.xtabline._buffers[buffer_number].special = 1, but scrollbar buffer is displayed.

Yes because that buffer has always a visible window.

xtabline doesn't show buffers that have non-empty `buftype` (scratch buffers), unless they're handled on purpose. You should open an issue there and tell the maintainer to set `buftype` to `nofile` since it's not a file. xtabline will ignore it then.

**Comment by yutakatay** [comment]
I'll try it. Thank you for your advice.

**Comment by yutakatay** [comment]
This is a common way to create a scratch buffer in Neovim.

```vim
syntax enable
filetype plugin indent on

if has('vim_starting')
  let s:pluin_manager_dir='~/.vim/plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif

call plug#begin('~/.vim/plugged')
Plug 'mg979/vim-xtabline'
call plug#end()

let g:xtabline_settings = get(g:, 'xtabline_settings', {})
let g:xtabline_settings.tabline_modes = [ 'buffers', 'arglist']

let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
let opts = {'relative': 'win', 'width': 10, 'height': 2, 'col': 10,
  \ 'row': 10, 'anchor': 'NW', 'style': 'minimal'}
let win = nvim_open_win(buf, 0, opts)
```

But even with this setting, it will show up in XTabNextBuffer. buftype is nofile.

**Comment by mg979** [comment]
Can you try now?

**Comment by yutakatay** [comment]
Thank you. It worked properly as expected :+1:

**Comment by mg979** [comment]
Thanks for reporting.
