### ISSUE TITLE
Don't display a buffer on tab

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#2]
### Bug report

I updated new master. But I think it is broken. I want to show in tab when I open a new buffer. But it only shows when I opened a second time.
dfc6957ece33161150c5d4719e33f1c9352f8e5a commit is OK.
Is this expected?

### Info

vim version: NVIM v0.4.0-778-g974b43fd7
Kernel: Linux argon 5.1.7-arch1-1-ARCH 
OS: Arch Linux
commit hash: 19b7513513efa33ab8364320abbc4d7cbb93b8d8

### screen shot

![do-not-display](https://user-images.githubusercontent.com/8683947/59147978-44000180-8a3d-11e9-8551-6fbc46c21a5c.gif)

### minimal vimrc

``` vim
if !((has('python') || has('python3') || has('ruby') || has('nvim'))
      \ && v:version > 703)
  echo 'Not load a plugin. Required +python/+python3/+ruby support or nvim'
  finish
endif


if has('vim_starting')
  let s:pluin_manager_dir='~/.vim/plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
  if !isdirectory(expand(s:pluin_manager_dir))
    call system('mkdir -p ' . s:pluin_manager_dir)
    call system('git clone --depth 1 https://github.com/junegunn/vim-plug.git '
        \ . s:pluin_manager_dir . '/autoload')
  end
endif

call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-plug',
      \ {'dir': '~/.vim/plugged/vim-plug/autoload'}

Plug 'mg979/vim-xtabline'

call plug#end()
```

**Comment by mg979** [comment]
Thanks for reporting, the last commit on master has caused this. I'm looking for a fix.

**Comment by mg979** [comment]
I think it's fixed?

**Comment by yutakatay** [comment]
Fixed. Thank you :smile:
