### ISSUE TITLE
How to achieve hybrid (buffers+tabs) mode?

### ISSUE THREAD

**Issue by wookayin** [mg979/vim-xtabline#20]
I would like to have a hybrid mode combining the `buffers` mode and the `tabs` mode: when there is only one tab present, the modes work like `buffers`, and as `tabs` when there are more than two tabs.

From doc:
```
                                                      *xtabline-tabline_modes*

    let g:xtabline_settings.tabline_modes = ['tabs', 'buffers', 'arglist']

        The modes that can be put in this list are:

        - |tabs|:       similar to the default vim tabline, with CWD
        - |buffers|:    buffer names
        - |arglist|:    the files in the arglist, as shown by |:args|

        The modes can be cycled with <F5> (default mapping).
```

Would it be possible to have a combined, hybrid mode as a built-in feature? Or how can one implement this on their own using the existing modes. Also, I would want to suppress messages like `Showing buffers`.

Thank you for your help!

**Comment by mg979** [comment]
You could set up some autocommands, that check the number of tabs. For example on `Tabnew` you do

    silent XTabMode tabs

and on `TabClosed` you check the number of tabs, if it's only one you do

    silent XTabMode buffers

**Comment by wookayin** [comment]
Thanks. I wrote custom autocommands like this:

```
" Use tabs mode if there are 2+ tabs, or buffers mode if there is only one
augroup TablineHybridMode
  autocmd!
  autocmd TabEnter,TabNew,TabClosed * call s:tabline_automode()
augroup end
function! s:tabline_automode(...) abort
  if !v:vim_did_enter | return | endif
  if tabpagenr('$') >= 2
    silent XTabMode tabs
  else
    silent XTabMode buffers
  endif
endfunction
```

I disabled executing the function during vim startup (note that TabEnter is triggered on vim initialization) because otherwise the plugin might not have been fully loaded yet (this can be a tiny bug that can be fixed). Specifically, `autoload/xtabline/funcs.vim`.

```
Error detected while processing function <SNR>2_tabline_automode[3]..xtabline#cmds#run[3]..<SNR>192_change_mode:
line   33:
E716: Key not present in Dictionary: "msg"
```

One small problem is that the xtabline updates twice (e.g. when closing the second tab, the list of buffers are first updated and then quickly changed to the buffer mode) which looks a bit awkward. Other than this, however, the behavior I wanted to have works well for me.

**Comment by mg979** [comment]
I would remove TabEnter.

**Comment by wookayin** [comment]
That would work, but `TabNew` can still take place before full initialization (e.g. `vim +tabnew ...`). So the same error can happen.

**Comment by mg979** [comment]
Yes that error happens, I'll have to check it out. Initialization is complete after `VimEnter` currently.

You can use `silent!` instead of `silent` to skip errors. Anyway I'd remove `TabEnter` because it's additional processing every time you change tab, and it's useless here.

**Comment by mg979** [comment]
I made initialization complete normally (before VimEnter), so that error shouldn't appear anymore. I think this can be closed.
