### ISSUE TITLE
Error on loading session

### ISSUE THREAD

**Issue by yanzhang0219** [mg979/vim-xtabline#21]
Hello,

This plugin is definitely amazing. I have been using it for a long time. Just now I wanted to try its session management feature. I got an issue.

Firstly, I am using neovim on macOS. 
When I try to load a session, the fzf window is open but there is an "illegal option" error in it. I attached a screenshot below. 

![image](https://user-images.githubusercontent.com/11582667/106222162-d49bd000-6193-11eb-84de-0bbac15a0f0d.png)

I believe this issue is caused by the simplified version of `stat` command in macOS. 

Thank you very much. 

Update:
Next, I tried the Startify's session management. I opened two buffers and saved the session. Then when I tried to load the session, xtabline only showed one buffer (the default mode is 'buffers', and lazyload is set to 0). I have to enter the ex command line and then quit to make all the buffers show out, or toggle 'tab' mode followed by toggling 'buffers' mode back.

**Update2**:
I installed the latest GNU `stat` and `date` commands, and change all `stat` and `date` in `xtabline/fzf.vim` to `gstat` and `gdate`. Then the issue is solved. The time can be shown correctly in the session selection window. I will open a PR for this latter.
However, when I load a session that contains more than one buffer, only one buffer instead of all the buffers in this loaded session will be shown on the tabline.

**Comment by mg979** [comment]
I don't have a mac and I don't know what the syntax of the `stat` command is in mac. Maybe you can make a PR.

**Comment by yanzhang0219** [comment]
Sure. But how about the second issue? I am not sure whether it is related to macOS as well. Can you reproduce it on Linux? I will try to describe it in detail below.

I open vim with a buffer open. Then I use `:edit filename ` to open another buffer. Now it has two buffers. Next, I save the session by `XTabSaveSession`. Then I close vim totally. Next, I reopen vim, and without opening any buffer, I try to load the session by `XTabLoadSession`. It is loaded successfully, however, on the tabline, only one buffer name is shown there. This session has two buffers open, so I think after loading the session, all the buffers in it should be displayed immediately on the tabline, not just only one, right?

Next, as long as I bring the ex command line by pressing `:`, and quit it immediately without inputting anything, other buffer names will appear on the tabline. I also tried `XTablineUpdate` command (I have a key mapping for it), and this command could make other buffers appear as well. 

Thank you so much!

**Comment by mg979** [comment]
I can't reproduce in linux. What is your primary mode? `tabs` or `buffers`? Because if it's `tabs` it's normal. The other buffer is in the buffers list anyway, so it's loaded.

**Comment by mg979** [comment]
Also update master, if you didn't.

**Comment by yanzhang0219** [comment]
My primary mode is `buffers`. 

When I set it to `tabs`, then after loading a session, when I toggle it to `buffers` mode, all buffers will be displayed on the tabline. However, if the primary is `buffers`, only one buffer is displayed. 

BTW, my xtabline is the latest.

**Comment by mg979** [comment]
I updated master, can you try now?

**Comment by yanzhang0219** [comment]
Oh Yes!. It works now!! Really nice. 

Thank you very much.

**Comment by mg979** [comment]
Thanks

**Comment by yanzhang0219** [comment]
Hi, 
I already open a PR to solve the issue, i.e., "illegal option" errors in the fzf window of the session loading and deletion. 
Thank you.
