### ISSUE TITLE
Closed buffer is still on the tabline

### ISSUE THREAD

**Issue by yanzhang0219** [mg979/vim-xtabline#23]
Hello,

It seems the tabline doesn't get refreshed when the current buffer is closed via the command `XTabCloseBuffer`, and even via the built-in `bdelete` command. I attached a short video as a demo below. I have two buffers. When I closed one, it was still on the tabline.

https://user-images.githubusercontent.com/11582667/106373829-51fd4700-6332-11eb-94f0-f9c53e360406.mov

BTW, as I remember this issue seemed not existing before https://github.com/mg979/vim-xtabline/commit/4d434cb616f7747afe9baa713e57006108689b8b, but I am not sure.
Thank you very much.

**Comment by mg979** [comment]
Should be fixed, hoping it won't break something else.
