### ISSUE TITLE
Not display all buffers when switching tab

### ISSUE THREAD

**Issue by yanzhang0219** [mg979/vim-xtabline#24]
Hello,

I got another issue regarding the buffer display when tab switching. Firstly, the default mode is `buffers`. And I have already updated xtabline to the latest.

How to reproduce
1. open neovim with one buffer open
2. run `:tabedit filename` to open a new tab. 
    On the tabline it shows `2/2` along with two buffers, so far so good. 
3. run `:tabprevious` to switch to the other tab. 
    On the tabline, it shows `1/2`, **however, only the first buffer is shown on the tabline. Here is the issue. I think all the buffers should be displayed, right?**
4. To make all buffers to be displayed on the tabline, I have to run `:XTablineUpdate`, or switch to the `tabs` mode and then switch back to the `buffers` mode.

I attached a short video as a demo below:

https://user-images.githubusercontent.com/11582667/106390648-3d569880-639e-11eb-9c73-5c6ad8bd06cc.mov

Thank you very much.

**Comment by mg979** [comment]
Thanks and sorry for these issues, they all appeared after I decided to refilter buffers less ofter. I use `tabs` as main mode so I didn't notice them. It should be fixed.

**Comment by yanzhang0219** [comment]
Thanks. No worries. I use `buffers` as the main mode and I can catch the potential bugs/issues. 🤗
