### ISSUE TITLE
Help can be more usefull

### ISSUE THREAD

**Issue by lesar** [mg979/vim-xtabline#26]
On help I read on row 207:  
```
BUFFERS-MODE                                                *xtabline-buffers*
==============================================================================
                                                      *xtabline-select-buffer*
  Plug                              Mapping~
  <Plug>(XT-Select-Buffer)          [count] <BS>

  Command                           Mapping~
  XTabNextBuffer                  [count] ]b
  XTabPrevBuffer                  [count] [b
  XTabCloseBuffer                *q
  XTabHideBuffer                  *h
  XTabMoveBuffer                 *m
  XTabMoveBufferNext          *]
  XTabMoveBufferPrev          *[
  XTabPinBuffer                     *p
```

I'm using Ubuntu 20.04 and vim 8.2  
>  XTabNextBuffer                    [count] ]b

work in normal mode but is not write in help
>  XTabMoveBuffer                    *m

work only if use \\x before and this too is not write.  
The * before the key is for what?  
Is this * tell me I have to use \\x ?  
before the \\x m the [count] work to set the buffer number position to move:  
\\x [count]]m  
\\x 3m move the current buffer to 3 position  

I like this plugin and I'm moving to use it, so I **not** know it well.  

If the help was writing thinking to beginners I think it will be more usefull.

Please, my English is not good so forgive it: my intention is to be polite and help the project.

best regards,
Leoanardo

**Comment by mg979** [comment]
https://github.com/mg979/vim-xtabline/blob/654675222adde47c9d72caa400e35c7e680fe5a1/doc/xtabline.txt#L160-L170

**Comment by lesar** [comment]
Ok thank you
