### ISSUE TITLE
How do I disable this plugin on a specific file type or buffer

### ISSUE THREAD

**Issue by 13396433778** [mg979/vim-xtabline#27]
I want to disable this plugin for certain file types or buffers. What should I do

**Comment by 13396433778** [comment]
just leave it undisplayed

**Comment by mg979** [comment]
What do you mean, what should it display?

**Comment by 13396433778** [comment]
I want this plug-in not to be displayed for a particular file type

**Comment by mg979** [comment]
`:help xtabline-override`
