### ISSUE TITLE
Make tab line invisible when only one tab is open

### ISSUE THREAD

**Issue by RyannDaGreat** [mg979/vim-xtabline#28]
Is there a way to make the tab line invisible when I'm only using one tab?

Default vim behaviour is to leave the tabline invisible when only one tab exists, saving space in the terminal. But i noticed that when I install this plugin, it makes the tab bar visible all the time even when opening a single file. 

Thank you,
Ryan

**Comment by mg979** [comment]
It makes sense, thanks.

**Comment by RyannDaGreat** [comment]
Thank you!
