### ISSUE TITLE
Compatiability with Taboo

### ISSUE THREAD

**Issue by RyannDaGreat** [mg979/vim-xtabline#29]
There's a vim plugin called "Taboo" that lets you rename Vim tabs. It works with vanilla vim tabs, but with this plugin it doesn't seem to work (the tabs keep their default names after using the TabooRename command). Is there any way to make this work?

For example, if I create two tabs, and in the second tab use the ":TabooRename MySecondTab" command, the tab should then be called MySecondTab

Here's the Taboo plugin:
https://github.com/gcmt/taboo.vim

Thank you!

**Comment by mg979** [comment]
`:help xtabline-rename`

Although tab labels work a bit differently.

**Comment by mg979** [comment]
I reworked it and now it behaves like in Taboo.

**Comment by RyannDaGreat** [comment]
Thank you so much! This is much better
