### ISSUE TITLE
Why did you change the default tabline_modes?

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#3]
Why did you change the default mode?
https://github.com/mg979/vim-xtabline/commit/011b217b758f75a17666eaa884c1ae9aa7f08c41

I love buffers mode :smile: Do you plan to stop supporting it in the future?? :thinking:

**Comment by mg979** [comment]
I only changed the default mode, so that a new installation looks like default vim, but with a slightly better tabline, I made most options optional. You can set it in the vimrc, like:
```vim
let g:xtabline_settings = {
      \ 'relative_paths':           0,
      \ 'theme':                    'slate',
      \ 'tabline_modes':            ['buffers', 'tabs', 'arglist'],
      \ 'use_tab_cwd':              1,
      \ 'buffer_filtering':         1,
      \}
```

**Comment by yutakatay** [comment]
I was able to restore with it. I decided to continue using this plugin :+1:

Thank you :smile:

**Comment by mg979** [comment]
I reworked a lot this plugin lately, sorry if many things are different.
