### ISSUE TITLE
No filenames in List of command XTabListTabs

### ISSUE THREAD

**Issue by mfilser** [mg979/vim-xtabline#31]
Hello,
thank you for your plugin. I tried it today and it looks really good.

I tried to use the command XTabListTabs, but the filenames aren't displayed.

Here's a screenshot:
![grafik](https://user-images.githubusercontent.com/13166201/137531544-50c1bb8e-3a2c-46c5-8a19-59ca9fd424e0.png)

Here is my vim version (neovim on Debian 11)
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-wroKTq/vim-8.2.2434=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lacl -lattr -lgpm -ldl -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.32/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm -L/usr/lib `

Maybe it's related to my previous Pull Request #30 

Thank you a lot in advance for any hint,
Best Regards,
Martin

**Comment by mg979** [comment]
Filenames shouldn't be displayed, only the tab working directory and the number of buffers relative to that directory. There's a currently a bug when loading sessions, because the plugin is paused and tabs working directory aren't immediately updated. Anyway showig filenames wasn't the purpose of the command (I never use it personally, I think it's useless, tab names are usually informative enough).

I guess some commands in this plugin are just too much. If you use nvim I'm redoing it in lua at https://github.com/mg979/tabline.nvim, it'll look better and cut off some stupid stuff. It's still a WIP though.

**Comment by mfilser** [comment]
Do you mean tab names in the list of the command XTabListTabs or the tab names at the top?

**Comment by mg979** [comment]
I see this when I run XTabListTabs

![1](https://user-images.githubusercontent.com/26169924/137533898-850948d3-1544-4844-a2c7-e65185fc357d.png)

`Name` would be the tab name, because you can give names to tabs with `:XTabNameTab`, otherwise it's empty.

**Comment by mfilser** [comment]
> Anyway this command will be dropped in the new version, so I'd just forget about it.

Oh, really? For me i am looking for a fast way to jump to tabs of files which i already opened.
Besides this, it would be also useful (for me) to open the file from filesystem if it isn't opend in a tab yet.

**Comment by mg979** [comment]
The tab label shows the filename by default already, it shows the name if you give it a name. But that command doesn't show the filename, it wasn't meant to be. I'll do it if I have time but right now I don't have it, sorry :).

**Comment by mg979** [comment]
> For me i am looking for a fast way to jump to tabs of files which i already opened.

By the way fzf.vim has a `:Windows` command that does what you want, I think I can close this.

**Comment by mfilser** [comment]
I see.
Thank you a lot for the hint. I am also looking forward any for enhancements of your plugin :slightly_smiling_face:
