### ISSUE TITLE
An 8-color tab theme

### ISSUE THREAD

**Issue by RyannDaGreat** [mg979/vim-xtabline#34]
Hi! Could you please add a simple 8-color tab theme? All of the themes currently require a terminal that can display 256 colors, unlike the Windows terminal. Right now, if you run in 8-color vim, the selected tab is white, along with the other unselected tabs - making it hard to see which tab I'm in. 

Or otherwise, is there a way to add a custom theme in my .vimrc without forking this repo?

Thank you!,
Ryan Burgert

**Comment by mg979** [comment]
Does this work?

https://github.com/mg979/vim-xtabline/pull/14#issuecomment-687659881

You should modify the theme of course, only using 8-bit colors. If you make a good one please post it here and I might add it.

**Comment by RyannDaGreat** [comment]
Hi @mg979 , thank you so much for the super quick response! I tried it out. The original one didn't work because the plugin loads after my .vimrc is run, so I modified it and got this:

```
function CustomTheme()
  return {
  \"XTSelect":      [ 'black', 'blue',   'NONE',   'NONE',   1 ],
  \"XTSelectMod":   [ 'black', 'blue',   'NONE',   'NONE',   1 ],
  \"XTVisible":     [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \"XTVisibleMod":  [ 'blue', 'black',   'NONE',   'NONE',   1 ],
  \"XTHidden":      [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \"XTHiddenMod":   [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \"XTExtra":       [ 'blue', 'black',   'NONE',   'NONE',   1 ],
  \"XTExtraMod":    [ 'blue', 'black',   'NONE',   'NONE',   1 ],
  \"XTSpecial":     [ 'blue', 'black',   'NONE',   'NONE',   1 ],
  \"XTNumSel":      [ 'black', 'blue',   'NONE',   'NONE',   0 ],
  \"XTNum":         [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \"XTCorner":      [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \"XTFill":        [ 'blue', 'black',   'NONE',   'NONE',   0 ],
  \}
endfunction

au VimEnter * call xtabline#hi#generate('custom_theme', CustomTheme())
```

**Comment by mg979** [comment]
Sure, create (if you want) a theme and name it `8bit`.
