### ISSUE TITLE
Feature Suggestion: Git Integration

### ISSUE THREAD

**Issue by RyannDaGreat** [mg979/vim-xtabline#36]
I have an idea for a feature: an indicator on each tab that tells you if it has changes to the previous git commit.

Just like Xuyuanp/nerdtree-git-plugin marks folders and files that are dirty, perhaps this would be possible in tabs? It would mark uncommitted tabs as dirty, so you can see which ones that have been edited.

Right now it already shows a `*` next to tabs that have been modified but not saved. Perhaps we could also have markers for files that are saved but not committed?

**Comment by mg979** [comment]
No thanks. Statuslines are better suited for git badges anyway.
