### ISSUE TITLE
buffer mode do not show the tabline

### ISSUE THREAD

**Issue by Sharelter** [mg979/vim-xtabline#37]
Hi, 
I freshly installed the xtabline plug via vim-plug on my neovim.
The tabmode works just fine, but the buffer mode do not show the tabline when I have multiple buffers and change to buffer mode.
Any suggestions ?

**Comment by mg979** [comment]
No idea what's the issue, maybe a mapping? But why don't you try https://github.com/mg979/tabline.nvim if you're on neovim? It's mostly the same.

**Comment by Sharelter** [comment]
I switched to tabline.nvim, now the problem is that when I only have one tab, and no bufferline is displayed.
Here is my configration of tabline.nvim

And is there anyway to let the tabs_bandage indicator show the "serial number" of buffers which is the output of  `:buffers`
so I can use :[N]buffer ( N is the number showed on the "bufferline" ) to directly switch to the buffer I wanna

```
-------------------------------------------------------------------------------
-- Settings
-------------------------------------------------------------------------------
-- These are the default values, if you delete a key, default will still be used
-- To know what the settings do, read :help tnv-settings

local settings = {
  main_cmd_name             = 'Tabline',
  filtering                 = false,
  cwd_badge                 = true,
  tabs_badge                = {
    fraction = true,
    left = true,
    visibility = {'buffers'}
  },
  label_style               = 'sep',
  show_full_path            = false,
  show_unnamed              = true,
  clickable_bufline         = true,
  max_recent                = 10,
  modes                     = { 'auto', 'buffers'},
  mode_badge                = { buffers = 'B', auto = 'A'},
  mapleader                 = '<leader><leader>',
  default_mappings          = false,
  cd_mappings               = false,
  theme                     = 'default',
  show_icons                = true,
  colored_icons             = true,
  icon_spacing              = '  ',
  ascii_only                = false,
  scratch_label             = '[Scratch]',
  unnamed_label             = '[Unnamed]',
}
```

**Comment by mg979** [comment]
>And is there anyway to let the tabs_bandage indicator show the "serial number" of buffers which is the output of :buffers
so I can use :[N]buffer ( N is the number showed on the "bufferline" ) to directly switch to the buffer

I think it's `label_style` (set it to `bufnr`).

>now the problem is that when I only have one tab, and no bufferline is displayed.

What do you mean? If your main mode is `auto` (from your config it seems it is), tabline is in buffer mode if there is only one tab. I tried your config, I see no problems. Maybe you think it's in tabs mode but it's actually in buffer mode. Can you read the `A` in the top left corner? It means it's in auto mode.

The only problem I see is that right now you can't have different `label_style`s in different mode (like separator in tabs mode and buffer number in buffers mode), but for the rest I don't see problems.

**Comment by Sharelter** [comment]
THX, the label now works the way I want.
And about another problem:
![image](https://user-images.githubusercontent.com/63940407/190574349-8b1f0091-c065-4195-8118-1391f8bf9707.png)
Looks like this image: I have one tab and two windows, each of two windows have different buffer.
But it looks like tabline.nvim is not activated under this situation.
When I have two or more tabs, both auto and buffers will work.
![image](https://user-images.githubusercontent.com/63940407/190575122-c38eb4d6-2ee5-4315-bb73-d676059eca7d.png)
![image](https://user-images.githubusercontent.com/63940407/190575214-d1542233-3f6e-41b1-b27d-70b94f6b808f.png)

**Comment by mg979** [comment]
I think you have `showtabline` set to 1, set it to 2 in your vimrc

    :set showtabline=2

**Comment by Sharelter** [comment]
All works, THX for your help :)
