### ISSUE TITLE
next/prev_buffer() does not work any more since  commit 3c7264ed0

### ISSUE THREAD

**Issue by skyblueee** [mg979/vim-xtabline#4]
my setting(linux):

> let g:xtabline_settings = {}
> let g:xtabline_settings.tabline_modes = ['buffers', 'tabs', 'arglist']
> let g:xtabline_settings.buffer_filtering = 0
> "let g:xtabline_settings.override_airline = 0
> nmap `<tab>` :XTabNextBuffer`<cr>`
> nmap `<s-tab>` :XTabPrevBuffer`<cr>`
> nmap `<BS>` <Plug>(XT-Select-Buffer)

Neither <Tab> nor :XTabNextBuffer<cr> works any more since:

> commit 3c7264ed0cb9a3d0a6e9dc880ae04a6ae315d41c
> Author: mg979 <mg1979.git@gmail.com>
> Date:   Fri Oct 4 21:00:30 2019 +0200
> Rewritten functions for buffer selection

**Comment by mg979** [comment]
Thanks for reporting, it should be working now, can you confirm? thanks

**Comment by skyblueee** [comment]
yes, it works. thanks.
