### ISSUE TITLE
Please update doc/tags when you update the master branch

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#5]
doc/tags often conflict when updating using vim-plug. Because vim-plug updates the tag  automatically with every update. https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins
I'm in trouble every time I have to resolve conflicts.

This is not updated now.

```
@@ -60,4 +60,5 @@ xtabline-tab-todo     xtabline.txt    /*xtabline-tab-todo*
 xtabline-tab_format    xtabline.txt    /*xtabline-tab_format*
 xtabline-tabline_modes xtabline.txt    /*xtabline-tabline_modes*
 xtabline-tabs_show_bufname     xtabline.txt    /*xtabline-tabs_show_bufname*
+xtabline-wd_type_indicator     xtabline.txt    /*xtabline-wd_type_indicator*
 xtabline.txt   xtabline.txt    /*xtabline.txt*
```

**Comment by mg979** [comment]
Sorry, I have removed the tags file entirely. Can you update master again and see if it's fixed?

**Comment by yutakatay** [comment]
Fixed! Thank you :wink:
