### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by Innei** [mg979/vim-xtabline#6]
```
Error detected while processing function xtabline#hi#init[2]..xtabline#hi#apply_theme[7]..
29:
line   13:
E492: Not an editor command:  guifg=#af0000 gui=bold cterm=bold
```

![image](https://user-images.githubusercontent.com/41265413/72213535-e4665900-352b-11ea-8f1d-3d991d6b993a.png)

and the nvim version.
![image](https://user-images.githubusercontent.com/41265413/72213575-15df2480-352c-11ea-9f20-cf4c495e9eaa.png)

**Comment by mg979** [comment]
Probably due to colorscheme, I'll fix it asap.

**Comment by mg979** [comment]
Is it fixed?

**Comment by Innei** [comment]
yes, it worked. Thanks.
