### ISSUE TITLE
Tab renaming or cooperability with taboo.vim

### ISSUE THREAD

**Issue by wookayin** [mg979/vim-xtabline#7]
[taboo.vim](https://github.com/gcmt/taboo.vim) is another tab-related vim plugin which allows us to customize or change tab names to be displayed.

This plugin also have a touch on `tabline` (so does taboo.vim), which means that they won't cooperate. That being said, it would be great to support displaying renamed tab titles (e.g. `:TabooRename <tab-title>`), as [vim-airline](https://github.com/vim-airline/vim-airline) does being [aware of these third-party plugins](https://github.com/vim-airline/vim-airline/blob/v0.11/doc/airline.txt#L1114).

**Comment by mg979** [comment]
Tabs can be renamed, `XTabNameTab {name}` is the command, it's in the documentation. The tab name appears in the top-right corner for the current tab, or on the tab label for other tabs.

**Comment by wookayin** [comment]
My apologies for not carefully searching the documentation. I tried a couple of things like 'rename', 'naming', 'name tab' but there were no match. But there was `XTabNameTab`, thanks! It'd be also good to improve on the documentation.

**Comment by mg979** [comment]
Yes sorry documentation is a bit long and should be improved, I'll add a faq.
