### ISSUE TITLE
paste: Error executing lua: vim.lua:203: Vim(endfunction):E171: Missing :endif

### ISSUE THREAD

**Issue by yutakatay** [mg979/vim-xtabline#8]
vim version: Neovim v0.5.0-404-g49cd750d6
OS: ArchLinux

Input
`:%s/[paste-here]` (paste or middle click)

Error message
`paste: Error executing lua: vim.lua:203: Vim(endfunction):E171: Missing :endif`

I think this error has been occurring since https://github.com/mg979/vim-xtabline/commit/17efbb83c4a6640a0a08733172468a7e537ee28e

**Comment by mg979** [comment]
I can't reproduce with neovim stable (0.4.3) and xterm-256color (xfce4-terminal). What terminal are you using?

Also, when you say:

`:%s/[paste-here]` (paste or middle click)

How do you `paste` if not with middle click? Middle click works without errors for me.

**Comment by yutakatay** [comment]
I'm sorry, I didn't have enough research.

I'm using alacritty 0.4.1.
And, This is minimal vimrc. It's only for neovim.

```vim
set nocompatible

set inccommand=split

set runtimepath^=~/.vim/plugged/vim-xtabline
syntax on
filetype plugin indent on
```


`Paste` is terminal paste function in alacritty. It's `C-S-V` for me.
`{ key: V,        mods: Control|Shift,    action: Paste               }`
This error occurs with a mouse-middle-click. But `<C-r>"` does not occur.

**Comment by mg979** [comment]
Ok I could reproduce it, I'll see what causes it.

**Comment by mg979** [comment]
It should be fixed, it's a bit weird, I think it's a nvim bug, but at least it shouldn't be happening again. Please reopen if it doesn't work.

**Comment by yutakatay** [comment]
it works fine! Thank you :+1:
