### ISSUE TITLE
Using lazyloading results in binding opening buffer.

### ISSUE THREAD

**Issue by 7415963987456321** [mg979/vim-xtabline#9]
Hey, I've been trying out xtabline for the past few days and I have the following set:
` let g:xtabline_lazy = 0`
However it results in the backspace key being bound to opening the buffer menu for some reason, even though I have set
`let g:xtabline_settings.enable_mappings = 0`
This is on the latest git version of xtabline.
Let me know if you need more information to reproduce.
Thanks.

**Comment by mg979** [comment]
I guess you meant you have this?

    let g:xtabline_lazy = 1

Because it happened with lazy loading.

**Comment by 7415963987456321** [comment]
@mg979 Oh sorry, I actually copied the current state of the line, which I had changed to 0 to get rid of the binding issue. So what I meant to say was that I run into the issue when that setting is set to 1.
